developit/preact-compat

- README.md
In webpack, we need to use `resolve.alias`, instead `module.alias` =)
> Fix instructions to use with webpack

- src/index.js
Current implementation of `createClass` autobinds every method including `constructor`. It leads to the bug where child component is being unmounted/mounted completely instead of updating.
The bug occurs in the following line: https://github.com/developit/preact/blob/master/src/vdom/component.js#L108
`inst.constructor` is never equal to `childComponent` because of autobinding.
I've implemented straightforward fix, but I think it would be better to revisit autobinding and make it more consistent with React behavior. For example, React doesn't autobind built-in methods, such as `render`, `setState`, `componentDidMount`, `componentWillUnmount`, etc.
> Do not autobind constructor

- src/index.js
- test/index.js
My colleagues and I ran into an issue with preact-compat where `getInitialState` wasn't being called for components created with `createClass`. What we found was that the `Component` function was being called prior to `getInitialState` being added to the actual object, so when the constructor tried to call that method it didn't exist. We switched the extend call in preact compat to come first to fix this issue.
> `getInitialState` not being called on components created with createClass

- src/index.js
React Hot Loader 3 uses React Proxy which relies on `isReactComponent` flag set on `React.Component` prototype.
See:
* gaearon/react-hot-loader version 3 `lib/patch.dev.js` (`require()`'s block)
* gaearon/react-proxy version 2 `src/createClassProxy.js` -> (`proxyClass` function)
* commit facebook/react@8364418 (2015-10-02) `src/isomorphic/modern/class/ReactComponent.js`
> Set Component.prototype.isReactComponent

- src/index.js
- test/component.js
As discussed in developit/preact#280, `cloneElement()` was not patching String refs, which would then be passed into Preact unmodified, resulting in an exception.
/cc @robbiewxyz @aweber1
> Fix string refs in cloneElement()

- src/index.js
> fix onchange trigger twice for select box

- src/index.js
- test/component.js
Components relying on React's `componentWillReceiveProps` expect `props.children` to pass single children without an array.  I've swapped the order of `propsHook` and `componentWillReceiveProps` on line #374 so that the behavior of our props processing will be more compatible with React.
I also wrote up a test for this behavior.
> single out children before componentWillReceiveProps

- README.md
babel-plugin-module-resolver allows you to use babel on the server as easily as webpack and browserify on the client.
> added HOWTO to alias in Babel

- src/index.js
This should prevent the change event from firing twice when clicking on a checkbox, addressing this issue: https://github.com/developit/preact/issues/358
> Delete onChange attribute when aliased

- src/index.js
- test/component.js
Fixes #239.
Let me know if anything isn't clear or is just plain wrong. Happy to make changes :)
> Merge mixin return values

- src/index.js
There were some differences to the following methods
that caused Preact to act differently than React:
- Children.map
- Children.forEach
- Children.count
> Make the Children API compatible with React

- package.json
- src/index.js
- test/index.js
Fixes https://github.com/developit/preact-compat/issues/261
This adds support for [this functionality](https://facebook.github.io/react/docs/uncontrolled-components.html#default-values) which I missed from the first time I tried out preact-compat. Somehow I forgot that it was missing until I went to release my app to some beta users today and realized it was kinda broken as it is haha.
I worked on this with @developit so hopefully it doesn't need much massaging to merge 👍
> Add support for defaultValue to preact-compat

- src/index.js
As suggested in the comment to the merged PR (ref: https://github.com/developit/preact-compat/pull/247) the event normalisation has broken the support for onChange on radio buttons. This is a potential fix
> Fix for the radio button not working with onChange

- src/index.js
React's [SyntheticEvent](https://facebook.github.io/react/docs/events.html) wraps the native DOM event and expose it via a `nativeEvent` property.
In some instances you may wish to stop immediate propagation. In this case your code may look like this:
``` javascript
onClick = (e) => {
e.stopPropagation();
e.nativeEvent.stopImmediatePropagation();
};
```
Since Preact [doesn't use synthetic events](https://github.com/developit/preact/issues/36) we can safely call `stopImmediatePropagation` directly on the event object. This change allows React code to work without modification.
> Expose the nativeEvent object to match React's Synthetic Event wrapper.

- src/index.js
- test/index.js
@developit .
Now it export instance of `ContextProvider`, not passed vnode.
> Should export instance when call renderSubtreeIntoContainer.

- package.json
- rollup.config.js
According to jsforum/jsforum#5 `jsnext:main` should contain the transpiled version with the exception of ES6 modules.
Users can include the library without having to apply the babel transformations needed by this package
> Correct jsnext:main

- src/index.js
- test/index.js
cloneElement - if children are provided in the second
argument of cloneElement they are ignored.
`cloneElement(component, { children })` will now properly apply children to `component`
fixes #316
> Allow children in the props argument of cloneElement

- src/index.js
There are cases when `this.props.chidren` is undefined and toArray was returning an array containing undefined instead of an empty array.
> Fix Children.toArray when passed undefined

- package.json
- rollup.config.js
- src/index.js
- test/component.js
I goofed up and totally missed that @tkh44 (#352) and @DonnieWest (#351) were already working on this when I started looking at #358.
The big differences here are
- updating the error message to match what `prop-types` spits out
- changing the variables names from `Foo` in the test, which had to be done because somewhere in the code the I think FB guards against spitting out the same `console.error` message multiple times. Meaning the variable names have to be different.
Let me know what you all think.
> Another prop-types lib solution

- src/index.js
- test/index.js
Add context for callback function in "renderSubtreeIntoContainer" because behavior in the ReactJS
> ReactJS compatibility

- src/index.js
Follow codes make a problem
````
const children2 = React.Children.toArray(children)
// const children2 = [...React.Children.toArray(children)]
if (loop) {
const firstChild = children2[0]
const lastChild = children2[children2.length - 1]
children2.push(firstChild)
children2.unshift(lastChild)
}
````
> toArray return new array

- src/index.js
- test/component.js
the bug breaks antd-mobile picker component.
* https://github.com/ant-design/ant-design-mobile/blob/master/components/picker/index.tsx#L72
* https://github.com/react-component/m-picker/blob/master/src/MultiPicker.tsx#L20
> bugfix: array[object] data children going to be an object

- src/index.js
- test/jsx.js
Instead of trying to normalize, which breaks preact-compat-nested non-compat components, let's install `props.className` as an alias pointing to `props.class`.
> props.className as an alias of props.class

- src/index.js
- test/svg.js
Properly transform `vectorEffect` into `vector-effect`
> Add vectorEffect to the list of camel case properties

- src/index.js
Fixes: 
"Object does not support the method for" error in IE11.
> IE11 seems to define Symbol but without the method 'for'

- src/index.js
- test/component.js
> Bind getDefaultProps to the class so statics can be read (#420)

- src/index.js
The thing is… it doesn't really work. The console log doesn't show any error, but at the same time nothing renders.
> Add unstable_batchedUpdates to exported functions (#411)

- README.md
Upgrading packages for a project, I got tripped up by `react-dom-factories` in ag-grid. After taking some time to work out quite what was going on I found the PR for the support, but no documentation on it - so this should help out others in the same situation as me.
> Add `react-dom-factories` usage to README

- src/index.js
> Make process shim not necessary on production environments

- src/index.js
Needs a test or two.
Note: this does not implement [event bubbling redirection](https://reactjs.org/docs/portals.html#event-bubbling-through-portals), since doing so would be rather difficult in Preact.
> Implement createPortal(). Fixes #452.

- package.json
- src/index.js
- test/index.js
Also had to lock `preact-render-to-string` at 3.7.2 as 3.8.0 is a breaking change.  See https://github.com/developit/preact-render-to-string/issues/59
> findDOMNode should return element if given element (fixes #493)

- src/index.js
Found this while debugging why `prop-types` didn't work in `preact-cli` (see: https://github.com/developit/preact-cli/issues/627).
Turns out the reason is that our global `DEV` variable was always set to `false` when `preact-compat` was bundled. The reason being that we checked if `process` is available:
```js
const DEV = typeof process !== 'undefined' && process.env && process.env.NODE_ENV!=='production';
```
But bundlers typically don't shim the `process` object and instead replace all string occurrences of `process.env.NODE_ENV` with `development` for example. After the bundler has done its magic the code would now look like this:
```js
const DEV = typeof process !== 'undefined' && process.env && 'development'!=='production';
```
Note that `process` is still `undefined` which is why …
> Fix DEV always being false in webpack

- README.md
Unfortunately Browserify says you can't make global transforms from package.json:
https://github.com/browserify/browserify#btransformtr-opts
"If opts.global is true, the transform will operate on ALL files, despite whether they exist up a level in a node_modules/ directory. Use global transforms cautiously and sparingly, since most of the time an ordinary transform will suffice. You can also not configure global transforms in a package.json like you can with ordinary transforms."
> Adding Aliasify global transform options

- .travis.yml
This PR runs tests via node 10 instead of the long unsupported version 4.
> Use node 10 for Travis

- package.json
This helps usher folks to `preact/compat`, and avoids serious issues that arise when (accidentally) including `preact-compat` with preact 10+, including [`Object.prototype` pollution](https://github.com/cssinjs/jss/pull/1091#issuecomment-484502359).
> Disable preact-compat with preact 10+

- lib/ReactFragment.js
- lib/ReactPerf.js
- lib/ReactTransitionEvents.js
- package.json
- rollup.config.js
- src/index.js
- test/component.js
- test/index.js
- test/jsx.js
- test/lib/ReactComponentWithPureRenderMixin.js
- test/lib/ReactTransitionEvents.js
- test/lib/ReactTransitionGroup.js
- test/lib/update.js
- test/svg.js
This basically just consumes and re-exports https://github.com/valotas/preact-context so people don't have to do extra steps.
> Add createContext
